import './style.css'

const phone = '+49 1573 903 90 00'
const tel = '+4915739039000'
const wa = 'https://wa.me/4915739039000?text=Guten%20Tag%20Herr%20Dag%2C%20ich%20m%C3%B6chte%20einen%20Schaden%20melden.'
const icon = (name) => {
  const paths = {
    phone: '<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.2-1.2a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/>',
    arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>', check: '<path d="m5 12 4 4L19 6"/>',
    camera: '<path d="M14.5 4 16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3l1.5-3h5Z"/><circle cx="12" cy="13" r="3"/>',
    truck: '<path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',
    shield: '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>', menu: '<path d="M4 7h16M4 12h16M4 17h16"/>'
  }; return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]}</svg>`
}

document.querySelector('#app').innerHTML = `
<header class="header"><div class="top"><div class="wrap"><span>Mobiler Kfz-Sachverständiger in OWL</span><div><a href="mailto:gutachten@dagtransporte.de">gutachten@dagtransporte.de</a><a href="tel:${tel}">${phone}</a></div></div></div><div class="nav wrap"><a class="brand" href="#start" aria-label="DAG Gutachten Startseite"><img src="/kfz-sachverstaendiger-logo.jpg" alt="DAG Gutachten"><span><b>DAG</b><small>GUTACHTEN</small></span></a><button class="menu" aria-label="Menü öffnen" aria-expanded="false">${icon('menu')}</button><nav aria-label="Hauptnavigation"><a href="#leistungen">Leistungen</a><a href="#ablauf">Ablauf</a><a href="#fuhrparks">Für Betriebe</a><a href="#ueber-uns">Über uns</a><a href="#einsatzgebiet">Einsatzgebiet</a></nav><a class="btn btn-dark desktop-cta" href="#kontakt">Schaden melden ${icon('arrow')}</a></div></header>
<main id="start">
<section class="hero"><div class="hero-media"><img src="/v23-startseite-mercedes-autohaus-hero-2x-seo.jpg" alt="Professionelle Schadenaufnahme an einem Mercedes vor einem Autohaus" width="1200" height="1500"><div class="shade"></div></div><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow"><span></span>Zertifizierter Kfz-Sachverständiger</p><h1>Ihr Schaden.<br><em>Unser Gutachten.</em></h1><p class="hero-lead">Unabhängige Unfallgutachten und Fahrzeugbewertungen – persönlich, präzise und direkt bei Ihnen vor Ort in Schloß Holte-Stukenbrock und ganz OWL.</p><div class="actions"><a class="btn btn-accent" href="#kontakt">Schaden jetzt melden ${icon('arrow')}</a><a class="btn btn-glass" href="tel:${tel}">${icon('phone')} ${phone}</a></div><div class="proof"><span>${icon('check')} Für Geschädigte kostenfrei*</span><span>${icon('check')} Pkw, Transporter & Lkw</span><span>${icon('check')} Mobile Begutachtung</span></div></div><aside class="quick-card"><p>Unfall gehabt?</p><strong>Jetzt direkt handeln.</strong><span>Schicken Sie uns Fotos, Standort und Rückrufnummer. Wir melden uns persönlich.</span><a href="${wa}" target="_blank" rel="noopener">Per WhatsApp starten ${icon('arrow')}</a><small>* Bei einem unverschuldeten Haftpflichtschaden trägt in der Regel die gegnerische Versicherung die Gutachterkosten.</small></aside></div><div class="scroll">SCROLL <i></i></div></section>
<section class="trust"><div class="wrap trust-grid"><div><b>Unabhängig</b><span>Ihre Interessen im Fokus</span></div><div><b>Vor Ort</b><span>Am Fahrzeugstandort</span></div><div><b>Direkt</b><span>Persönlich erreichbar</span></div><div><b>Präzise</b><span>Technisch sauber dokumentiert</span></div></div></section>
<section class="section intro" id="leistungen"><div class="wrap"><div class="section-head"><p class="kicker">Unsere Leistungen</p><h2>Klare Fakten.<br><span>Starke Grundlage.</span></h2><p>Ein Schaden ist mehr als eine beschädigte Stelle. Wir dokumentieren den Zustand, ordnen den Schaden technisch ein und schaffen eine belastbare Grundlage für die weitere Bearbeitung.</p></div><div class="services"><article class="service featured"><span class="number">01</span>${icon('shield')}<h3>Unfallgutachten</h3><p>Schadenaufnahme, Beweissicherung und Kalkulation nach einem fremdverschuldeten Unfall – inklusive Prüfung relevanter wirtschaftlicher Positionen.</p><a href="#kontakt">Gutachten anfragen ${icon('arrow')}</a></article><article class="service"><span class="number">02</span>${icon('camera')}<h3>Wertgutachten</h3><p>Fundierte Fahrzeugbewertung für Kauf, Verkauf, hochwertige Fahrzeuge, Firmenfahrzeuge und interne Entscheidungen.</p><a href="#kontakt">Bewertung anfragen ${icon('arrow')}</a></article><article class="service"><span class="number">03</span>${icon('truck')}<h3>Fuhrparks & Nutzfahrzeuge</h3><p>Flexible Begutachtung für Transporter, Lkw, Anhänger und Auflieger – auf dem Hof, an der Rampe oder in der Werkstatt.</p><a href="#fuhrparks">Mehr erfahren ${icon('arrow')}</a></article></div></div></section>
<section class="process section" id="ablauf"><div class="wrap"><div class="section-head light"><p class="kicker">So funktioniert es</p><h2>Vier Schritte.<br><span>Ein klares Ergebnis.</span></h2></div><div class="steps"><article><b>01</b><h3>Schaden melden</h3><p>Telefonisch, per WhatsApp oder über das Formular.</p></article><article><b>02</b><h3>Termin abstimmen</h3><p>Fahrzeugdaten, Standort und Schadenbild kurz klären.</p></article><article><b>03</b><h3>Vor-Ort-Aufnahme</h3><p>Fotodokumentation, Messung und technische Prüfung.</p></article><article><b>04</b><h3>Gutachten erhalten</h3><p>Als Grundlage für Versicherung, Werkstatt oder Kanzlei.</p></article></div></div></section>
<section class="fleet section" id="fuhrparks"><div class="wrap split"><div class="image-block"><img src="/lkw-frontschaden-aufnahme-seo.jpg" alt="Schadenaufnahme an einem Lkw" loading="lazy"><span>PKW · TRANSPORTER · LKW · AUFLIEGER</span></div><div class="content"><p class="kicker">Für Betriebe & Partner</p><h2>Wenn Stillstand<br><span>keine Option ist.</span></h2><p>Fahrzeuge sind Teil Ihrer täglichen Leistung. Deshalb müssen Schäden schnell, nachvollziehbar und wirtschaftlich sauber erfasst werden.</p><ul><li>${icon('check')} Speditionen und Fuhrparks</li><li>${icon('check')} Autohäuser und Werkstätten</li><li>${icon('check')} Vermieter und Fahrzeugbetriebe</li><li>${icon('check')} Versicherungen und Schadenregulierer</li></ul><a class="text-link" href="#kontakt">Gewerbliche Anfrage stellen ${icon('arrow')}</a></div></div></section>
<section class="about section" id="ueber-uns"><div class="wrap split reverse"><div class="content"><p class="kicker">Jonathan Dag</p><h2>Technischer Blick.<br><span>Klare Worte.</span></h2><p>DAG Gutachten steht für persönliche Erreichbarkeit, nachvollziehbare Dokumentation und unabhängige Bewertung. Als zertifizierter Kfz-Sachverständiger begleitet Jonathan Dag private und gewerbliche Auftraggeber vom ersten Kontakt bis zum verwertbaren Gutachten.</p><blockquote>„Sie sprechen direkt mit dem Sachverständigen, der Ihr Fahrzeug begutachtet.“</blockquote><a class="btn btn-dark" href="#kontakt">Persönlich Kontakt aufnehmen ${icon('arrow')}</a></div><div class="image-block portrait"><img src="/about-jonathan-dag-mercedes-ipad-seo.jpg" alt="Kfz-Sachverständiger Jonathan Dag bei der Fahrzeugbegutachtung" loading="lazy"></div></div></section>
<section class="region section" id="einsatzgebiet"><div class="wrap"><div class="section-head"><p class="kicker">Mobil in Ostwestfalen-Lippe</p><h2>Wir kommen<br><span>zum Fahrzeug.</span></h2><p>Mobile Schadenaufnahme für Privatkunden, Betriebe und Fuhrparks rund um Schloß Holte-Stukenbrock.</p></div><div class="places"><b>Schloß Holte-Stukenbrock</b><b>Bielefeld</b><b>Gütersloh</b><b>Paderborn</b><b>Verl</b><b>Rheda-Wiedenbrück</b><b>Oerlinghausen</b><b>Hövelhof</b><b>Detmold</b><b>Herford</b></div></div></section>
<section class="contact section" id="kontakt"><div class="wrap contact-grid"><div><p class="kicker">Jetzt Schaden melden</p><h2>Der nächste Schritt<br><span>ist ganz einfach.</span></h2><p>Schicken Sie uns die wichtigsten Angaben. Wir prüfen Ihren Fall und melden uns persönlich zurück.</p><div class="direct"><a href="tel:${tel}">${icon('phone')}<span><small>Direkt anrufen</small><b>${phone}</b></span></a><a href="mailto:gutachten@dagtransporte.de"><span class="mail">@</span><span><small>E-Mail schreiben</small><b>gutachten@dagtransporte.de</b></span></a></div></div><form id="lead-form"><label>Ihr Name<input name="name" autocomplete="name" required placeholder="Vor- und Nachname"></label><label>Telefonnummer<input name="phone" autocomplete="tel" required placeholder="Für den Rückruf"></label><label>Worum geht es?<select name="type"><option>Unfallgutachten</option><option>Wertgutachten</option><option>Fuhrpark / Nutzfahrzeug</option><option>Sonstige Anfrage</option></select></label><label>Kurze Nachricht<textarea name="message" rows="3" placeholder="Fahrzeug, Schaden und Standort"></textarea></label><label class="consent"><input type="checkbox" required><span>Ich stimme der Verarbeitung meiner Angaben zur Bearbeitung der Anfrage zu.</span></label><button class="btn btn-accent" type="submit">Anfrage per WhatsApp senden ${icon('arrow')}</button></form></div></section>
</main>
<footer><div class="wrap footer-grid"><div class="footer-brand"><a class="brand" href="#start"><img src="/kfz-sachverstaendiger-logo.jpg" alt=""><span><b>DAG</b><small>GUTACHTEN</small></span></a><p>Unabhängige Kfz-Gutachten für Privatkunden, Unternehmen und Fahrzeugpartner in OWL.</p></div><div><h3>Leistungen</h3><a href="#leistungen">Unfallgutachten</a><a href="#leistungen">Wertgutachten</a><a href="#fuhrparks">Fuhrparks & Lkw</a><a href="#fuhrparks">Partner</a></div><div><h3>Kontakt</h3><a href="tel:${tel}">${phone}</a><a href="mailto:gutachten@dagtransporte.de">gutachten@dagtransporte.de</a><p>Siemensweg 3<br>33758 Schloß Holte-Stukenbrock</p></div><div><h3>Rechtliches</h3><a href="https://dag-gutachten.de/impressum.php">Impressum</a><a href="https://dag-gutachten.de/datenschutz.php">Datenschutz</a><a href="https://dag-gutachten.de/agb.php">AGB</a><a href="https://dag-gutachten.de/unterlagen.php">Auftragsunterlagen</a></div></div><div class="wrap copyright"><span>© 2026 DAG Gutachten</span><span>Zertifizierter Kfz-Sachverständiger · OWL</span></div></footer>
<div class="mobile-bar"><a href="tel:${tel}">${icon('phone')} Anrufen</a><a href="${wa}" target="_blank" rel="noopener">WhatsApp</a><a href="#kontakt">Schaden melden</a></div>`

const menu = document.querySelector('.menu'), nav = document.querySelector('.nav nav')
const closeMenu = () => {
  nav.classList.remove('open')
  document.body.classList.remove('menu-open')
  menu.setAttribute('aria-expanded', 'false')
  menu.setAttribute('aria-label', 'Menü öffnen')
}
menu.addEventListener('click', () => {
  const open = !nav.classList.contains('open')
  if (open) {
    nav.classList.add('open')
    document.body.classList.add('menu-open')
    menu.setAttribute('aria-expanded', 'true')
    menu.setAttribute('aria-label', 'Menü schließen')
  } else closeMenu()
})
nav.addEventListener('click', closeMenu)
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeMenu() })
document.querySelector('#lead-form').addEventListener('submit', (event) => { event.preventDefault(); const d = new FormData(event.currentTarget); const m = `Guten Tag Herr Dag, ich möchte eine Anfrage stellen.%0A%0AName: ${encodeURIComponent(d.get('name'))}%0ATelefon: ${encodeURIComponent(d.get('phone'))}%0AAnliegen: ${encodeURIComponent(d.get('type'))}%0ANachricht: ${encodeURIComponent(d.get('message'))}`; window.open(`https://wa.me/4915739039000?text=${m}`, '_blank', 'noopener') })
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('visible') }), { threshold: .12 })
document.querySelectorAll('.section-head,.service,.steps article,.split,.contact-grid').forEach((el) => observer.observe(el))
